version: "3"

services:

  elasticsearch:
    image: amazon/opendistro-for-elasticsearch:0.7.1
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xmx4096m"
    networks:
    - efk-idranalysis
    volumes:
    # Elasticsearch database
    - ./volumes/es:/usr/share/elasticsearch/data

  fluentd:
    build: ./fluentd
    networks:
    - efk-idranalysis
    volumes:
    # Fluentd configuration
    - ./fluentd/:/fluentd/etc/:ro
    # Fluentd file position record
    - ./volumes/fluentd/:/fluentd/pos/
    # Aggregated Haproxy HTTP logs
    - /uod/idr/versions/idr-analysis-logs-combined/:/idranalysis-haproxy-logs/:ro
    - /uod/idr/versions/nginx-logs-combined/prod-merged-agg/:/idr-nginx-logs:ro
    #- ./logs-haproxy/:/idranalysis-haproxy-logs/:ro
    #- ./logs-nginx/:/idr-nginx-logs:ro

  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:0.7.1
    environment:
      ELASTICSEARCH_URL: https://elasticsearch:9200
    networks:
    - efk-idranalysis

  nginx:
    image: library/nginx:1.15.8
    networks:
    - efk-idranalysis
    ports:
    - "12381:8080"
    volumes:
    # Nginx configuration
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    # Nginx basic auth
    - ./nginx/passwd:/etc/nginx/passwd:ro

networks:
  efk-idranalysis:

#volumes:
